### ISSUE TITLE
Call to a member function setadditional_data() on a non-object

### ISSUE THREAD

**Issue by Airals** [juicymedialtd/Magento-BarclaysPSPID#1]
Hi,
Getting the following error on a new server:
Call to a member function setadditional_data() on a non-object in /var/www/pagesoflyndhurst.co.uk/public_html/app/code/local/Juicy/Barclayspspid/controllers/paymentController.pgp on line 208

This error comes from making a payment to Barclay and being re diverted back.

**Comment by j-webb** [comment]
This looks like it could be a problem with the back office configuration. Navigate to the EPDQ back office and go to:
Configuration > Technical Information > Transaction Feedback

Firstly, make sure the HTTP redirection URLs match the following
www.YOURDOMAIN.com/barclayspspid/payment/process/

Secondly, check the box that says "I would like to receive transaction feedback parameters on the redirection URLs"

Then, make sure all of the following are in the "Selected" list:
AAVADDRESS
AAVCHECK
AAVMAIL
AAVNAME
AAVPHONE
AAVZIP
ACCEPTANCE
AMOUNT
BIC
BIN
BRAND
CARDNO
CN
COMPLUS
CURRENCY
CVCCHECK
ECI
ED
IP
IPCTY
NCERROR
ORDERID
PAYID
PM
STATUS
SUBBRAND
TRXDATE
VC 
Then, below these options, tick the box that says "I would like Barclaycard to re-launch the "end of transaction" (post-payment request/redirection) process if required." Once you have done this, enter new SHA-IN and SHA-OUT codes, making sure they are exactly the same as each other. We recommend using the SHA-1 option. Then paste these codes into the Magento Extension configuration

Next, navigate to the Checks for e-commerce section on your back office. Find the input for Data and origin verification and ensure that this and all other fields are input correctly (you can include more than one domain by using ; to separate). Ensure you have both http and https domains listed

Finally, ensure you have input your PSPID correctly in the Magento EPDQ module configuration (it is case sensitive)
